### ISSUE TITLE
Correct yarn command in README (or use npm command)

### ISSUE THREAD

**Issue by mok0230** [OpenZeppelin/defender-serverless#15]
In `README`, it currently says to install with:

```
yarn install defender-serverless
```

but this mashes up `yarn` and `npm` nomenclature. It would either be `yarn add defender-serverless` or `npm install defender-serverless`

**Comment by shahnami** [comment]
Nice catch, will get this updated :)

**Comment by shahnami** [comment]
Fixed in https://github.com/OpenZeppelin/defender-serverless/pull/23
