### ISSUE TITLE
Confirm level appears to have integer validation and cannot accept "safe" or "finalized"

### ISSUE THREAD

**Issue by mok0230** [OpenZeppelin/defender-serverless#16]
[This comment](https://github.com/OpenZeppelin/defender-serverless/blob/main/examples/defender-test-project/serverless.yml#L118) indicates that I can pass a value of "safe" or "finalized" to `confirm-level`, but I get the following error when I do so:

> Error:
> Configuration error at 'resources.Resources.sentinels.another-block-example': unsupported integer format

Also, nitpick, but looking ahead I'd suggest using "goerli" for the network there rather than "rinkeby".

**Comment by shahnami** [comment]
Fixed in https://github.com/OpenZeppelin/defender-serverless/pull/23
