### ISSUE TITLE
Add networks enum definition

### ISSUE THREAD

**Issue by zeljkoX** [OpenZeppelin/defender-serverless#20]
`network` field has currently type string.

We don't have linked documentation about possible values there. 

It would be best to provide enum with all possible options so users can get human readable errors in case they write unsupported network or network name with typo. 
We do this at couple other places and it is great.

Note: `network` field is used for Relayer and Contract Resources so there is bigger surface for errors.

**Comment by shahnami** [comment]
Fixed in https://github.com/OpenZeppelin/defender-serverless/pull/23
