### ISSUE TITLE
Resources type in documentation is empty

### ISSUE THREAD

**Issue by peersky** [OpenZeppelin/defender-serverless#49]
Trying to understand possible resources in serverless brings me to [this](https://github.com/OpenZeppelin/defender-serverless/blob/91ee5d7fd85e3ec78ba177c2fd8704a4ad436f72/src/types/docs/resources.md) page, and it is empty.

Expected: 
Resources schema should be documented there

**Comment by shahnami** [comment]
Thanks for catching that! I'm submitting a PR to fix this :)
