### ISSUE TITLE
Typo in the definitions schema

### ISSUE THREAD

**Issue by arbitrary-nomad** [OpenZeppelin/defender-serverless#57]
On line 106
https://github.com/OpenZeppelin/defender-serverless/blob/main/src/types/docs-schemas/definitions.schema.json#L106

`        "metric-p$refix": {` should be
`        "metric-prefix": {`

**Comment by shahnami** [comment]
Thanks for reporting this!
Fixed in https://github.com/OpenZeppelin/defender-serverless/pull/59
